# SCRIPTS/ssh_test_ping.sh - reads login user per tailnet hostname
# Line format - tailnet-hostname user
raspi-parishilton parishilton
raspi-desktop ryandevens
raspi-organizer ryan
artie-thinkpad-p51s-w10dg artie
